### ISSUE TITLE
Support Spanner `ROW DELETION POLICY`

### ISSUE THREAD

**Issue by ProPorygon** [cloudspannerecosystem/liquibase-spanner#224]
Spanner allows you to specify a `ROW DELETION POLICY` when creating a table (https://cloud.google.com/spanner/docs/ttl/working-with-ttl#googlesql_1).

Currently, a `modifySql` configuration is needed to specify this via `liquibase-spanner`. It would be ideal if this could be directly specified in `createTable` configurations.

**Comment by olavloite** [comment]
That is unfortunately not possible, as the Liquibase `createTable` change type has a fixed set of properties. See https://docs.liquibase.com/change-types/create-table.html for the available properties. None of them fit the `ROW DELETION POLICY` of Spanner.

A specific Liquibase dialect, like for example this one for Spanner, does not have the possibility of adding additional properties to the standard change types. So the only options that remain for this kind of vendor-specific database features are:
1. Add a `modifySql` change type.
2. OR: Define the `createTable` using the SQL format instead of YAML/XML/JSON.
